name: Build Android Debug APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Perhatikan bahwa langkah 'chmod' juga perlu working-directory
      - name: Grant execute permission for gradlew
        working-directory: ./easycontrolfork   # <-- TAMBAHKAN INI
        run: chmod +x gradlew

      - name: Build Project with Server-App Steps
        working-directory: ./easycontrolfork   # <-- DAN TAMBAHKAN INI
        run: |
          ./gradlew assembleDebug -p server
          ./gradlew copyDebug -p server
          ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          # Path untuk artifact juga perlu disesuaikan
          path: easycontrolfork/app/build/outputs/apk/debug/app-debug.apk
